version: '3'
services:
  zookeeper:
    image: zookeeper:latest
    restart: always
    container_name: sync-server-zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - /apps/sync-server/zookeeper/zk1/data:/data
      - /apps/sync-server/zookeeper/zk1/datalog:/datalog
    environment:
      ZOO_MY_ID: 1
    networks:
      - kafka_zk
  kafka:
    image: bitnami/kafka:3.4
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    depends_on:
      - zookeeper
    volumes:
      - /apps/sync-server/kafka/kafka1/data:/kafka
    networks:
      - kafka_zk
networks:
  kafka_zk:
